# Template pentru ingress cu SSL automat
# Înlocuiește {{DOMAIN}} cu domeniul tău și {{SERVICE_NAME}} cu numele serviciului
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{SERVICE_NAME}}-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-ssl-redirect@kubernetescrd
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - {{DOMAIN}}
    secretName: {{DOMAIN}}-tls
  rules:
  - host: {{DOMAIN}}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{SERVICE_NAME}}
            port:
              number: 80