apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: luna-frontend
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .Values.volto.hostname }}
    secretName: {{ .Values.volto.hostname }}-tls
  rules:
  - host: {{ .Values.volto.hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-volto
            port:
              number: 3000
