apiVersion: v2
name: lunasites-frontend
description: LunaSites Volto Frontend - React-based CMS Frontend
type: application
version: 1.0.0
appVersion: "latest"
home: https://github.com/LunaSitesTech/lunasites
sources:
  - https://github.com/LunaSitesTech/lunasites-frontend
maintainers:
  - name: LunaSites Team
    email: team@lunasites.com
keywords:
  - volto
  - react
  - frontend
  - cms
  - javascript
  - lunasites
annotations:
  category: Frontend