# LunaSites Frontend Configuration
replicaCount: 2

image:
  repository: ghcr.io/luna-sites/lunasites-frontend
  pullPolicy: Always
  tag: "latest"

imagePullSecrets:
  - name: ghcr-secret

nameOverride: ""
fullnameOverride: ""

# Service Account
serviceAccount:
  create: true
  annotations: {}
  name: ""

# Pod Configuration
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}

# Service Configuration
service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

# Ingress Configuration
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: lunasites.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Resource Configuration
resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"

# Health Checks
livenessProbe:
  httpGet:
    path: /
    port: 3000
  initialDelaySeconds: 60
  periodSeconds: 30
  timeoutSeconds: 10
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /
    port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

# Autoscaling
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

# Environment Variables
env:
  - name: RAZZLE_API_PATH
    value: "https://lunasites.local/api"
  - name: RAZZLE_INTERNAL_API_PATH
    value: "http://lunasites-backend:8080/Plone"
  - name: TZ
    value: "Europe/Bucharest"

# Backend Configuration
backend:
  serviceName: "lunasites-backend"
  servicePort: 8080

# Node Selection
nodeSelector: {}
tolerations: []
affinity: {}