apiVersion: v2
name: luna-frontend
type: application
version: 1.0.0
appVersion: "0.29.0"
description: luna frontend
icon: https://raw.githubusercontent.com/eea/helm-charts/main/sources/luna-frontend/luna.png
home: https://github.com/eea/luna-frontend
keywords:
  - CMS
