image:
  repository: ghcr.io/luna-sites/lunasites-frontend
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

timezone: Europe/Copenhagen

ingress:
  certificate: demo-industry-tls
  tls: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/configuration-snippet: |-
      more_set_headers 'Server HTTPS'
        'Strict-Transport-Security max-age=31536000; includeSubDomains; preload'
        "Expect-CT max-age=604800, report-uri='https://sentry.luna-sites.com/api/45/security/?sentry_key=0343e20fc4e0469790b6016561f032e3'"
        'X-Content-Type-Options "nosniff"'
        'X-XSS-Protection "1; mode=block"'
        "X-Frame-Options 'SAMEORIGIN'"
        "Referrer-Policy origin"
        "Content-Security-Policy default-src 'none'; object-src 'self'; base-uri 'self'; form-action 'self'; manifest-src https://demo-industry.01dev.luna-sites.com/site.webmanifest; media-src https://*.luna-sites.com; data:; connect-src 'self' https://*.luna-sites.com http://*.luna-sites.com https://europa.eu/webtools/ https://webanalytics.europa.eu https://geocode.arcgis.com  https://api.openaire.eu https://api.openaire.com https://api.zotero.org/ https://cdn.arcgis.com/ https://www.arcgis.com/ https://utility.arcgisonline.com/ https://js.arcgis.com/ https://services.arcgisonline.com  https://services.arcgis.com https://static.arcgis.com https://basemaps.arcgis.com/ https://*.arcgis.com/ https://*.eionet.europa.eu http://*.luna-sites.com; font-src 'self' data: https://cdnjs.cloudflare.com/ https://fonts.gstatic.com/ https://*.luna-sites.com https://cdn.arcgis.com/ https://js.arcgis.com/ https://*.eionet.europa.eu https://eea.maps.arcgis.com/; frame-src 'self'  https://europa.eu/  https://*.europa.eu/ https://*.luna-sites.com http://*.luna-sites.com https://eea.maps.arcgis.com/; img-src http: https: blob: data:; script-src 'self' 'unsafe-inline' 'unsafe-eval' blob: data: https://matomo.luna-sites.com https://europa.eu/webtools/ https://www.google.com/jsapi https://www.google.com/uds/ https://www.gstatic.com/ https://ajax.googleapis.com/  https://spreadsheets.google.com/ https://docs.google.com/ https://*.eionet.europa.eu https://*.luna-sites.com http://*.luna-sites.com https://d3js.org https://cdnjs.cloudflare.com https://code.jquery.com https://services.arcgis.com https://public.tableau.com/javascripts/api/tableau-2.8.0.min.js https://public.tableau.com/javascripts/api/tableau-2.7.0.min.js https://public.tableau.com/javascripts/api/tableau-2.6.0.min.js https://public.tableau.com/javascripts/api/tableau-2.5.0.min.js https://public.tableau.com/javascripts/api/tableau-2.4.0.min.js https://public.tableau.com/javascripts/api/tableau-2.3.0.min.js https://public.tableau.com/javascripts/api/tableau-2.2.2.min.js https://public.tableau.com/javascripts/api/tableau-2.1.2.min.js https://public.tableau.com/javascripts/api/tableau-2.0.3.min.js https://js.arcgis.com/ https://api.openaire.eu https://api.openaire.com https://api.zotero.org/ https://geocode.arcgis.com; frame-ancestors 'self' *.eionet.europa.eu *.luna-sites.com; style-src 'self' 'unsafe-inline' https://www.google.com/uds/ https://europa.eu/webtools/ https://fonts.googleapis.com/css2 https://js.arcgis.com/ https://api.openaire.eu https://api.openaire.com https://api.zotero.org/ https://ajax.googleapis.com/ https://www.gstatic.com/ https://*.eionet.europa.eu https://*.luna-sites.com https://cdnjs.cloudflare.com https://code.jquery.com; report-uri https://sentry.luna-sites.com/api/49/security/?sentry_key=0343e20fc4e0469790b6016561f032e3"
        'Permissions-Policy accelerometer=(), autoplay=(), camera=(), encrypted-media=(), fullscreen=(self), geolocation=(self), gyroscope=(), magnetometer=(), microphone=(), midi=(), payment=(), picture-in-picture=(), sync-xhr=(self), usb=()';
    nginx.ingress.kubernetes.io/proxy-body-size: 1024m
    nginx.ingress.kubernetes.io/proxy-read-timeout: "480"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "120"

ingressredirects:
  - enabled: false
    tls: true
    certificate: www.plone.luna-sites.com-tls
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hostname: www.plone.luna-sites.com

links:
  backend: backend-varnish.luna

volto:
  serviceType: NodePort
  hostname: plone.luna-sites.com
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 6
    # targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 60
  replicaCount: 1
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 256Mi
  environment:
    SENTRY_URL:
    SENTRY_AUTH_TOKEN:
    SENTRY_ORG:
    SENTRY_PROJECT:
    RAZZLE_SENTRY_DSN:
    RAZZLE_BACKEND_NAME: "luna-backend"
    RAZZLE_ALLOWED_CORS_DESTINATIONS:
    RAZZLE_MATOMO_URL:
    RAZZLE_MATOMO_SITE_ID:
    RAZZLE_MATOMO_SECOND_SITE_ID:
    RAZZLE_MATOMO_SECOND_TRACKER_URL:
    RAZZLE_INTERNAL_API_PATH: "http://backend:8080/Plone"
    RAZZLE_API_PATH: "https://luna.luna-sites.com/++api++"
    RAZZLE_PUBLIC_URL:
    VOLTO_VERSION: "18.22.0"
    VOLTO_ROBOTSTXT:
    RAZZLE_DISABLE_DRAFT_WATERMARK:
  annotations: {}
  livenessProbe:
    httpGet:
      path: /ok
      port: http
    periodSeconds: 20
    timeoutSeconds: 10
    initialDelaySeconds: 30
    failureThreshold: 6
    successThreshold: 1
  startupProbe:
    httpGet:
      path: /ok
      port: http
    periodSeconds: 5
    timeoutSeconds: 10
    initialDelaySeconds: 10
    failureThreshold: 12
    successThreshold: 1
  readinessProbe:
    httpGet:
      path: /ok
      port: http
    periodSeconds: 15
    timeoutSeconds: 10
    initialDelaySeconds: 60
    failureThreshold: 4
    successThreshold: 2

debug:
  addonsPath: /app/src/addons
  affinity: {}
  enabled: false
  environment: {}
  nodeSelector: {}
  podAnnotations: {}
  podSecurityContext: {}
  resources:
    limits:
      memory: 256Mi
    requests:
      memory: 128Mi
  securityContext: {}
  serviceType: NodePort
  tolerations: []

varnish:
  serviceType: NodePort
  serviceName: frontend-varnish
  port: 3000
  backend: "frontend-volto"
  resources:
    limits:
      memory: 256Mi
    requests:
      memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  environment:
    VARNISH_SIZE: "128M"
    VARNISH_DNS_TTL: "20s"
    VARNISH_BERESP_TTL: "60s"
    VARNISH_BERESP_GRACE: "120s"
    VARNISH_BERESP_KEEP: "120s"
    VARNISH_GZIP_ENABLED: "false"
    AUTOKILL_CRON: ""
  livenessProbe:
    httpGet:
      path: /ok
      port: http
    periodSeconds: 10
    timeoutSeconds: 10
    initialDelaySeconds: 30
    failureThreshold: 5
    successThreshold: 1
  startupProbe:
    httpGet:
      path: /ok
      port: http
    periodSeconds: 5
    timeoutSeconds: 10
    initialDelaySeconds: 10
    failureThreshold: 12
    successThreshold: 1
