apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: luna-api
  labels:
    {{- include "appl.labels" . | nindent 4 }}
    component: luna-api
  annotations:
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.plone.hostname }}
    http:
      paths:
      - path: /\+\+api\+\+(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ include "appl.fullname" . }}-plone
            port:
              number: 8080
  {{- if .Values.ingress.tls }}
  tls:
  - hosts:
    - {{ .Values.plone.hostname }}
    {{- if .Values.ingress.certificate }}
    secretName: {{ .Values.ingress.certificate }}
    {{- end  }}
  {{- end  }}
