{{- if .Values.plone.googleUrl }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: luna-google-admin
  labels:
    {{- include "appl.labels" . | nindent 4 }}
    component: luna-google-admin
  annotations:
    traefik.ingress.kubernetes.io/router.tls.certresolver: "letsencrypt"
    traefik.ingress.kubernetes.io/router.middlewares: "kube-system-ssl-redirect@kubernetescrd"
    nginx.ingress.kubernetes.io/rewrite-target: /VirtualHostBase/https/{{ .Values.plone.hostname }}:443/{{ .Values.plone.site }}/VirtualHostRoot/_vh_admin/{{ .Values.plone.googleUrl }}$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  ingressClassName: traefik
  rules:
  - host: {{ .Values.plone.hostname }}
    http:
      paths:
      - path: /{{ .Values.plone.googleUrl }}(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ include "appl.fullname" . }}-plone
            port:
              number: 8080
  tls:
  - hosts:
    - {{ .Values.plone.hostname }}
    secretName: {{ .Values.plone.hostname | replace "." "-" }}-tls
{{- end }}
