name: Deploy Helm Charts to GitHub Pages

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4
        with:
          version: "latest"

      - name: Package Charts
        run: |
          mkdir -p packages
          for chart in sources/*/; do
            if [ -f "$chart/Chart.yaml" ]; then
              helm package "$chart" -d packages/
            fi
          done

      - name: Generate Index
        run: |
          helm repo index packages --url https://luna-sites.github.io/luna-helm-charts/
          mv packages/* docs/

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./docs"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
